### ISSUE TITLE
Breakout-Room

### ISSUE THREAD

**Issue by UniKN** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#45]
ILIAS: 7.20
BBB: 2.0.2

Breakout rooms can no longer be created.
![grafik](https://user-images.githubusercontent.com/117639119/231726693-75b3ae4e-02a0-4351-9252-a280779ffbb7.png)

**Comment by xJuvi** [comment]
Hi,
first of all, for full support this plug-in required BBB 2.0.3 or above. 

But I can see what is happen here. If Breakout Rooms not enabled, the official api sents a disabled command. 

To solve this we must add a new option. 

Kind regards.

**Comment by thwien** [comment]
We noticed the same problem with the BBB plugin version 2.0.2 (branch "release_7") on Ilias 7.25. After downgrading to 2.0 (branch "release2.0") breakout rooms appear again.

The differences between create urls are:

Version 2.0.2: role=MODERATOR&excludeFromDashboard=false

Version 2.0: joinViaHtml5=true

The other parameters are still the same.

I have no clue why the parameters in version 2.0.2 causes this problem. The user has moderator privileges and it should be allowed to create breakout rooms. Output of API request getMeeting seems to be correct.

**Comment by thwien** [comment]
@xJuvi Thanks for your reply. Any news on update your API library?

Right now I run in the same issue again due to upgrading to Ilias 8 and I cannot fix it by branch "release2.0" due to limited support until Ilias 7.99.

Of course I would prefer the latest plugin version to run, but offering "breakout rooms" are essential for us.

In would appreciate if you can let me know any workaround to solve this issue.

**Comment by xJuvi** [comment]
hi @thwien 
the issue should be fixed with merging PR #53 

Maybe @jeph864  have a moment time to verify and merge the PR.

Kind regards

**Comment by thwien** [comment]
@xJuvi Thanks a lot for your very quick reply. :)

If PR #53 solves that problem, I will now try to pull this PR to my local copy as a workaround.

**Comment by xJuvi** [comment]
If you already use ILIAS7 with PR #58 this bug should be fixed.
